name: CI
on: 
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'yarn.lock'
      - 'babel.config.js'
      - 'jest.config.js'
      - 'tsconfig.json'

jobs:
  build:
    name: Build, lint, and test on Node 14.x and ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSX: true
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: yarn dev && yarn test --ci --maxWorkers=2

      - name: Build
        run: yarn build